### ISSUE TITLE
Feature request: libraries compiled with smaller `WORDSIZE` and `MAXN`

### ISSUE THREAD

**Issue by rburing** [a-maier/nauty-Traces-sys#10]
Nauty can be compiled with different values of `WORDSIZE` and `MAXN`, see e.g. section 16 of [nauty and Traces User’s Guide](https://pallini.di.uniroma1.it/nug28.pdf).

This crate does not expose those options, but it would be cool if it did.

See e.g. https://github.com/JuliaBinaryWrappers/nauty_jll.jl for comparison, which offers all the variants (for use in Julia).

**Comment by a-maier** [comment]
Added with version 0.9.0.
