### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by juliuskunze** [a-maier/nauty-Traces-sys#5]
Hi @a-maier, thank you for publishing these bindings, I found them extremely useful! I'd like to use your project for published research.

Would you mind [adding a licence](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)? Legally, [no one is allowed to use your code](https://choosealicense.com/no-permission/) without one.

In case you would like to use the [MIT licence](https://choosealicense.com/licenses/mit/), I prepared [a PR](https://github.com/a-maier/nauty-Traces-sys/pull/6) that you could just merge.

**Comment by a-maier** [comment]
Thanks for pointing this out. The license is Apache-2.0, the same as for nauty and Traces.

The license was already listed in the `Cargo.toml`. I have added a license file and a note in the readme.

**Comment by juliuskunze** [comment]
Great, thanks a lot!
